## Recoverable Errors with Result
1. 通常處理`Result<T, E>`會有好幾層的match expression, 可以利用`unwrap_or_else`和closures讓code看起來更簡潔
	```rust
	#use std::{fs::File, io::ErrorKind};
	#fn main() {
		let greeting_file = File::open("hello.txt").unwrap_or_else(|error| {
			if error.kind() == ErrorKind::NotFound {
				File::create("hello.txt").unwrap_or_else(|error| {
					panic!("Problem creating the file: {error:?}");
				})
			} else {
				panic!("Problem opening the file: {error:?}");
			}
		});
	#}
	```
	原本的寫法
	```rust
	#use std::{fs::File, io::ErrorKind};
	#fn main() {
		let greeting_file = match File::open("hello.txt") {
			Ok(file) => file,
			Err(error) => match error.kind() {
				ErrorKind::NotFound => match File::create("hello.txt") {
					Ok(fc) => fc,
					Err(e) => panic!("Problem creating the file: {e:?}"),
				},
				other_err => panic!("Problem opening the file: {other_err:?}"),
			},
		};
	#}
	```
2. `unwrap`和`expect`兩者在`Err` case時都會panic, 差別在於`expect`可以指定panic的錯誤訊息.
	```rust
	#use std::fs::File;
	#fn main() {
		let greeting_file = File::open("hello.txt")
			.expect("hello.txt should be included in this project");
	#}
	```
3. Propagating Errors: 在function內遇到errors時, 不做處理而直接回傳errors至caller,
   由caller決定如何處理.
4. Rust提供了`?` operator在遇到error時就early return error, error在回傳前會經過`from`
   function轉成return type定義的error type.
   `?`可以chaining method使用讓code更精簡.
	```rust
	use std::fs::File;
	use std::io::{self, Read};
	fn read_username_from_file() -> Result<String, io::Error> {
		let mut username = String::new();

		File::open("hello.txt")?.read_to_string(&mut username)?;

		Ok(username)
	}
	```
5. `?`也可以用在`Option<T>`, 只是early return `None`
	```rust
	fn last_char_of_first_line(text: &str) -> Option<char> {
		text.lines().next()?.chars().last()
	}
	```
6. main function預設的return type是`()`, 但也可以回傳`Result<(), Box<dyn Error>>`
